name: cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: cml
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #pip install -r requirements.txt
          pip install matplotlib
          pip install setuptools
          
          #cml publish data/images/violin.png --md >> report.md
          #cml publish data/images/correlation_matrix.png --md >> report.md
          cml publish data/images/groundtruth.png --md >> report.md
          #cml publish data/images/importance_original.png --md >> report.md
          cml send-comment report.md
