name: model-causal-inference

on: 
  push:
  pull_request:
    branches:
    - main
jobs:
  run:
    runs-on: ubuntu-latest 
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: | 
           pip install -r requirements.txt
        #python scripts/script.py
    #- name: run-tests
        #python -m unittest tests.test_script
        # Post reports as comments in GitHub PRs
          
          #cat results.txt >> report.md
          #cml send-comment report.md
